/* tslint:disable */
/* eslint-disable */
/**
 * RedCloor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderType,
    OrderTypeFromJSON,
    OrderTypeFromJSONTyped,
    OrderTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetOrder
 */
export interface GetOrder {
    /**
     * 
     * @type {number}
     * @memberof GetOrder
     */
    id?: number;
    /**
     * 
     * @type {OrderType}
     * @memberof GetOrder
     */
    orderType?: OrderType;
    /**
     * 
     * @type {string}
     * @memberof GetOrder
     */
    customerName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GetOrder
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetOrder
     */
    createdbyUser?: string | null;
}

export function GetOrderFromJSON(json: any): GetOrder {
    return GetOrderFromJSONTyped(json, false);
}

export function GetOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'orderType': !exists(json, 'orderType') ? undefined : OrderTypeFromJSON(json['orderType']),
        'customerName': !exists(json, 'customerName') ? undefined : json['customerName'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'createdbyUser': !exists(json, 'createdbyUser') ? undefined : json['createdbyUser'],
    };
}

export function GetOrderToJSON(value?: GetOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'orderType': OrderTypeToJSON(value.orderType),
        'customerName': value.customerName,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'createdbyUser': value.createdbyUser,
    };
}


