/* tslint:disable */
/* eslint-disable */
/**
 * RedCloor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderType,
    OrderTypeFromJSON,
    OrderTypeFromJSONTyped,
    OrderTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateOrder
 */
export interface UpdateOrder {
    /**
     * 
     * @type {OrderType}
     * @memberof UpdateOrder
     */
    orderType?: OrderType;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrder
     */
    customerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrder
     */
    createdByUserName?: string | null;
}

export function UpdateOrderFromJSON(json: any): UpdateOrder {
    return UpdateOrderFromJSONTyped(json, false);
}

export function UpdateOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderType': !exists(json, 'orderType') ? undefined : OrderTypeFromJSON(json['orderType']),
        'customerName': !exists(json, 'customerName') ? undefined : json['customerName'],
        'createdByUserName': !exists(json, 'createdByUserName') ? undefined : json['createdByUserName'],
    };
}

export function UpdateOrderToJSON(value?: UpdateOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderType': OrderTypeToJSON(value.orderType),
        'customerName': value.customerName,
        'createdByUserName': value.createdByUserName,
    };
}


